apiVersion: v1
kind: Secret

metadata:
  name: {{ include "vprofile.fullname" . }}-secret
  labels:
    {{- include "vprofile.labels" . | nindent 4 }}

type: Opaque

stringData:
  DB_USERNAME: {{ .Values.secret.databaseUsername | quote }}
  DB_PASSWORD: {{ .Values.secret.databasePassword | quote }}

  RMQ_USERNAME: {{ .Values.secret.rabbitmqUsername | quote }}
  RMQ_PASSWORD: {{ .Values.secret.rabbitmqPassword | quote }}